bundle script fix for mgit

diff --git a/bundle b/bundle
--- a/bundle
+++ b/bundle
@@ -2,16 +2,18 @@
 # make daily bundles for each platform, for downloading from the homepage.
 
 die() { echo "$@" >&2; exit 1; }
-cd "$(dirname "$0")" || die "Could not cd to script dir"
-[ -d luapower ] || die "Directory \"$PWD/luapower\" not found"
+cd "$(dirname "$0")" || die "Could not cd to script's dir"
+[ -d luapower ] || die "luapower dir not found"
 outdir="$PWD/www"; [ -d "$outdir" ] || die "Directory \"$outdir\" not found"
-which zip >/dev/null || die "zip not found."
+which zip >/dev/null || die "zip not found"
 
 files() {
 	(platform="$1"
-	luapower/git ls-cloned | while read pkg; do
-		luapower/git $pkg ls-files | while read f; do
+	cd luapower
+	./mgit ls | while read pkg; do
+		./mgit $pkg ls-files | while read f; do
 			[ "$f" = "${f%.exclude}" ] && \
+			[ "$f" = "${f#.mgit/}" ] && \
 			[ "${f#bin/*/}" = "${f#bin/$platform/}" ] && \
 				echo "luapower/$f"
 		done
