unimportant

diff --git a/nginx/nginx b/nginx/nginx
--- a/nginx/nginx
+++ b/nginx/nginx
@@ -1,26 +1,24 @@
-#!/bin/sh
+#!/bin/bash
+# nginx wrapper for the luapower.com website.
+# all it does is setting all the needed paths before starting nginx.
 
-OPENRESTY_DIR=/usr/local/openresty
-WWW_DIR=../www
-LUAPOWER_DIR=../..
+die() { echo "$@" >&2; exit 1; }
 
-# ------------------------------------------------------------
+# everything is done relative to this script's parent dir.
+cd "$(dirname "$0")/.." || die "Could not cd to \"$(dirname "$0")/..\"."
 
-cd "$(dirname "$(readlink "$0")")"
-DIR="$PWD"
+OPENRESTY_DIR="$PWD/openresty"; [ -d "$OPENRESTY_DIR" ] || die "Directory \"$OPENRESTY_DIR\" not found."
+LUAPOWER_DIR="$PWD/luapower";   [ -d "$LUAPOWER_DIR" ]  || die "Directory \"$LUAPOWER_DIR\" not found."
+WWW_DIR="$PWD/www";             [ -d "$WWW_DIR" ]       || die "Directory \"$WWW_DIR\" not found."
+NGINX_CONF="$PWD/nginx/conf/nginx.conf"; [ -f "$NGINX_CONF" ] || die "File \"$NGINX_CONF\" not found."
 
-cd "$DIR"; cd "$WWW_DIR"; WWW_DIR="$PWD"
-cd "$DIR"; cd "$LUAPOWER_DIR"; LUAPOWER_DIR="$PWD"
-cd "$DIR"
+which pandoc >/dev/null || echo "WARNING: Pandoc not installed. Documentation will not be visible."
 
-[ "$ENV" ] || {
-    [ -f ../env ] || { echo "../env file not found."; exit 1; }
-    ENV=`cat ../env`
-}
-
+# detect platform. Linux and OSX are supported.
 [ "$(uname -m)" != x86_64 ] && P=32 || P=64
-[ "${OSTYPE#darwin}" ] && P=osx$P || P=linux$P
+[ "${OSTYPE#darwin}" != "$OSTYPE" ] && P=osx$P || P=linux$P
 
+# configure Lua and ldd paths
 WWWL="$WWW_DIR/?.lua"
 LPB="$LUAPOWER_DIR/bin/$P"
 LPBL="$LPB/lua/?.lua"
@@ -28,14 +26,12 @@ LPBB="$LPB/clib/?.so"
 LPL="$LUAPOWER_DIR/?.lua"
 ORL="$OPENRESTY_DIR/lualib/?.lua"
 ORB="$OPENRESTY_DIR/lualib/?.so"
-SYSB="/usr/local/lib"
 
 export LUA_PATH="$WWWL;$LPBL;$LPL;$ORL"
 export LUA_CPATH="$LPBB;$ORB"
 export WWW_DIR="$WWW_DIR"
 export LUAPOWER_DIR="$LUAPOWER_DIR"
-export LD_LIBRARY_PATH="$LPB:$SYSB"
-export OSTYPE="$OSTYPE"
+export LD_LIBRARY_PATH="$LPB"
 
-exec "$OPENRESTY_DIR/nginx/sbin/nginx" -p "$DIR" \
-    -c "$DIR/conf/nginx.$ENV.conf" "$@"
+# finally, run nginx
+exec "$OPENRESTY_DIR/nginx/sbin/nginx" -p "$PWD/nginx" -c "$PWD/nginx/conf/nginx.conf" "$@"
